apiVersion: v1
kind: ConfigMap
metadata:
  name: bookingsystem-config
  namespace: bookingsystem
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  ACCEPT_EULA: "Y"
  MSSQL_PID: "Developer"