apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookingsystem-ingress
  namespace: bookingsystem
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: bookingsystem.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bookingsystem-service
            port:
              number: 80