apiVersion: v1
kind: Secret
metadata:
  name: bookingsystem-secrets
  namespace: bookingsystem
type: Opaque
stringData:
  SA_PASSWORD: "YourStrong!Passw0rd"
  CONNECTION_STRING: "Server=bookingsystem-db-0.bookingsystem-db;Database=BookingSystemDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;MultipleActiveResultSets=true"